/**
 * Child of Error Class used for handling when there is an error generated by any module of api
 *
 * @extends Error
 */
export class ApiError extends Error {
  public type: string;
  /**
   * Constructor method for the ApiError class.
   * @param {string} type Error type
   * @param {string} message Error message details
   */
  constructor(type: string, message: string) {
    super(message);
    this.type = type;
  }
}
